CREATE TABLE COMPANY_MEMBERS(
   ID INT PRIMARY KEY     NOT NULL,
   NAME           TEXT    NOT NULL,
   AGE            INT     NOT NULL CHECK(AGE > 17),
   ADDRESS        CHAR(50),
   SALARY         REAL    DEFAULT 50000.00
);

CREATE TABLE DEPARTMENT(
   ID INT PRIMARY KEY      NOT NULL,
   DEPT           CHAR(50) NOT NULL,
   HEAD_ID         INT      references COMPANY_MEMBERS(ID)
);

