insert into COMPANY_MEMBERS (id, name, age, address, salary) values (61, 'Misha', 69, 'Anjozorobe', 42564.28);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (62, 'Ina', 39, 'Reshetnikovo', 59480.16);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (63, 'Harriette', 69, 'Bergen', 55638.83);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (64, 'Cassondra', 24, 'Sinuknipan', 77181.49);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (65, 'Den', 35, 'Colima', 65087.85);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (66, 'Valaree', 58, 'Malati', 13187.19);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (67, 'Filberte', 39, 'Soca', 35114.43);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (68, 'Bastian', 52, 'Torres Novas', 15151.11);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (69, 'Florrie', 41, 'Shiroishi', 51631.85);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (70, 'Ariel', 37, 'Taquara', 90404.65);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (71, 'Amos', 30, 'Erdaobaihe', 47130.53);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (72, 'Mella', 59, 'Sydney', 98525.8);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (73, 'Gertruda', 59, 'Gorodets', 82333.77);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (74, 'Rowland', 69, 'Malya', 84405.59);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (75, 'Krystal', 25, 'White River', 32937.56);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (76, 'Georgeanne', 68, 'Uusikaupunki', 14281.52);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (77, 'Gilbertina', 48, 'Portela', 31064.43);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (78, 'Mame', 59, 'Xiaoqi', 22692.53);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (79, 'Kariotta', 56, 'Huddinge', 66290.92);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (80, 'Edouard', 65, 'Krajan Baru', 53968.8);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (81, 'Hilarius', 38, 'Cocieri', 45505.15);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (82, 'Harmon', 68, 'Taurisma', 14187.78);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (83, 'Willetta', 28, 'Korenovsk', 54087.26);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (84, 'Bartolemo', 62, 'Zhujiatai', 92493.23);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (85, 'Fairleigh', 56, 'Qionghai', 84924.68);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (86, 'Belvia', 27, 'Ballinroad', 50524.46);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (87, 'Layton', 25, 'Arnhem', 60861.8);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (88, 'Dall', 31, 'Cidamar', 54829.42);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (89, 'Rowena', 58, 'Berat', 10275.55);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (90, 'Teodorico', 47, 'Kunów', 59944.94);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (91, 'Dane', 66, 'Karakol', 48757.42);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (92, 'Imelda', 46, 'Huancaray', 39310.08);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (93, 'Tadeo', 32, 'Tiecun', 31843.82);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (94, 'Boot', 63, 'Peseng', 90804.45);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (95, 'Randee', 30, 'Maradi', 64569.48);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (96, 'Cthrine', 48, 'Phú Lộc', 4168.8);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (97, 'Penrod', 32, 'Cambuga', 90252.16);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (98, 'Bogart', 54, 'Zaleszany', 84064.12);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (99, 'Ramona', 54, 'Fayzabad', 41606.92);
insert into COMPANY_MEMBERS (id, name, age, address, salary) values (100, 'Northrup', 56, 'Xianxi', 77890.22);
